# Generated by Django 6.0.5 on 2026-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem_restaurant_menuitem_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
