# Generated by Django 6.0.5 on 2026-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_logos/'),
        ),
    ]
